### ISSUE TITLE
Add chez-soundio to Projects Using libsoundio

### ISSUE THREAD

**Issue by ul** [andrewrk/www.libsound.io#1]
Hey, I've made Chez Scheme bindings to your excellent libsoundio! They are here https://github.com/ul/chez-soundio

Taking this opportunity, I want to thank you for developing such a nice lib =)

**Comment by andrewrk** [comment]
Nice work. Thanks for reaching out, and thanks for the compliment.

**Comment by andrewrk** [comment]
wow, that sine example is pretty beautiful.
